#!/bin/bash -eu

PROJ="coreos-install"
ORG_PATH="github.com/coreos"
REPO_PATH="${ORG_PATH}/${PROJ}"

export GOBIN=${PWD}/bin
export GO15VENDOREXPERIMENT=1

echo "Building ${PROJ}..."
go install ${REPO_PATH}/cmd/${PROJ}

